import type { GoalWithTasks } from '$lib/goal/utils';
import { addWeeks, endOfWeek, lastDayOfQuarter, lastDayOfYear } from 'date-fns';

let id = 0;
export const learnToDrive: GoalWithTasks = {
	id: id++,
	name: 'learn to drive',
	isDone: true,
	deadline: lastDayOfQuarter(new Date()),
	tasks: [
		{
			id: 1,
			name: 'learn to drive',
			description: null,
			isDone: true,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 10)),
			categoryId: 1,
			goalId: 1,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
	],
};

export const cancelMyBankAccount: GoalWithTasks = {
	id: id++,
	name: 'cancel my bank account',
	isDone: false,
	deadline: lastDayOfQuarter(new Date()),
	tasks: [
		{
			id: 10,
			name: 'write the letter',
			description: null,
			isDone: false,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 1)),
			categoryId: 1,
			goalId: 1,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
		{
			id: 11,
			name: 'print my documents',
			description: null,
			isDone: true,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 1)),
			categoryId: 1,
			goalId: 1,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
		{
			id: 12,
			name: 'send a letter',
			description: null,
			isDone: false,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 1)),
			categoryId: 1,
			goalId: 1,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
	],
};

export const investMoney: GoalWithTasks = {
	id: id++,
	name: 'invest Money',
	isDone: true,
	deadline: lastDayOfYear(new Date()),
	tasks: [
		{
			id: 40,
			name: 'read about the best investment',
			description: null,
			isDone: false,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 5)),
			categoryId: 1,
			goalId: 4,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
		{
			id: 40,
			name: 'read about the best way to invest',
			description: null,
			isDone: false,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 6)),
			categoryId: 1,
			goalId: 4,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
		{
			id: 40,
			name: 'invest',
			description: null,
			isDone: false,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 7)),
			categoryId: 1,
			goalId: 4,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
	],
};

export const readTheGospelOfJohn: GoalWithTasks = {
	id: id++,
	name: 'read the gospel of John',
	isDone: false,
	deadline: lastDayOfQuarter(new Date()),
	tasks: [
		{
			id: 40,
			name: 'read until the chapter 5',
			description: null,
			isDone: false,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(new Date()),
			categoryId: 1,
			goalId: 4,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
		{
			id: 41,
			name: 'read until the chapter 10',
			description: null,
			isDone: false,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 1)),
			categoryId: 1,
			goalId: 4,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
		{
			id: 42,
			name: 'read until the chapter 15',
			description: null,
			isDone: false,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 2)),
			categoryId: 1,
			goalId: 4,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
		{
			id: 43,
			name: 'read until the chapter 21',
			description: null,
			isDone: false,
			startDate: null,
			endDate: null,
			duration: null,
			deadline: endOfWeek(addWeeks(new Date(), 3)),
			categoryId: 1,
			goalId: 4,
			isRecurring: false,
			recurringStartAt: null,
			recurringEndAt: null,
			recurringDaysOfWeek: [],
			recurringExceptions: [],
		},
	],
};

export const goals = [learnToDrive, cancelMyBankAccount, investMoney, readTheGospelOfJohn];
